/* eFootball Dreamers — Supabase connection settings */
const SUPABASE_URL="https://nvmcgiwdkdlfoethwetr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY="sb_publishable_nRxxHhlAcCweiDK1ZPxcaw_sP2AT8ko";
let dreamersSupabase=null;
async function getSupabase(){if(dreamersSupabase)return dreamersSupabase;const mod=await import("https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm");dreamersSupabase=mod.createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY);return dreamersSupabase}
function accountStyles(){if(document.getElementById("dreamersAuthStyles"))return;const s=document.createElement("style");s.id="dreamersAuthStyles";s.textContent=`.auth-modal{position:fixed;inset:0;z-index:99999;display:none;align-items:center;justify-content:center;padding:20px}.auth-modal.open{display:flex}.auth-backdrop{position:absolute;inset:0;background:rgba(0,0,0,.82);backdrop-filter:blur(8px)}.auth-card{position:relative;width:min(440px,100%);padding:30px;border:1px solid #17628e;border-radius:22px;background:linear-gradient(145deg,#081b2b,#03080d);box-shadow:0 30px 100px rgba(0,0,0,.75);color:#fff}.auth-card h2{margin:5px 0 8px;font-size:29px}.auth-sub{color:#8da7b9;font-size:12px;line-height:1.5;margin-bottom:20px}.auth-card label{display:block;color:#9ab0c0;font-size:10px;font-weight:800;letter-spacing:.7px;margin:13px 0}.auth-card input{display:block;box-sizing:border-box;width:100%;margin-top:7px;padding:13px 14px;border:1px solid #1b4058;border-radius:10px;background:#040c13;color:#fff;outline:none}.auth-card input:focus{border-color:#159fff;box-shadow:0 0 0 2px rgba(21,159,255,.13)}.auth-submit{width:100%;margin-top:8px}.auth-close{position:absolute;right:14px;top:8px;border:0;background:transparent;color:#7790a0;font-size:28px;cursor:pointer}.auth-switch{margin-top:16px;text-align:center;color:#71899a;font-size:10px}.auth-switch button{border:0;background:none;color:#42b9ff;cursor:pointer;font-weight:900}.auth-message{min-height:18px;margin:10px 0 0;color:#45c5ff;font-size:11px;font-weight:800}.auth-error{color:#ff7180}.auth-note{display:block;margin-top:14px;color:#60798b;font-size:9px;line-height:1.5}`;document.head.appendChild(s)}
function authModal(){accountStyles();let m=document.getElementById("dreamersAuthModal");if(m)return m;m=document.createElement("div");m.id="dreamersAuthModal";m.className="auth-modal";m.innerHTML=`<div class="auth-backdrop" onclick="closeAuth()"></div><div class="auth-card"><button class="auth-close" onclick="closeAuth()">×</button><p class="eyebrow">eFOOTBALL DREAMERS</p><h2 id="authTitle">Create your account</h2><p class="auth-sub" id="authSub">Join the community with a real online account.</p><form id="authForm"><label>Username<input id="authUsername" maxlength="24" autocomplete="username" placeholder="Dreamer99" required></label><label>Email<input id="authEmail" type="email" autocomplete="email" placeholder="you@example.com" required></label><label>Password<input id="authPassword" type="password" minlength="6" autocomplete="new-password" placeholder="At least 6 characters" required></label><button class="auth-submit" type="submit" id="authSubmit">Create Account →</button></form><p id="authMessage" class="auth-message" aria-live="polite"></p><div class="auth-switch"><span id="authSwitchText">Already have an account?</span> <button id="authSwitchBtn" type="button">Log in</button></div><small class="auth-note">Your password is handled by Supabase Authentication; this website does not store your password.</small></div>`;document.body.appendChild(m);m.querySelector("#authForm").addEventListener("submit",handleAuthSubmit);m.querySelector("#authSwitchBtn").addEventListener("click",()=>setAuthMode(authMode==="signup"?"login":"signup"));return m}
let authMode="signup";
function setAuthMode(mode){authMode=mode;const m=authModal(),title=m.querySelector("#authTitle"),sub=m.querySelector("#authSub"),u=m.querySelector("#authUsername"),submit=m.querySelector("#authSubmit"),sw=m.querySelector("#authSwitchText"),btn=m.querySelector("#authSwitchBtn");m.querySelector("#authMessage").textContent="";m.querySelector("#authForm").reset();if(mode==="login"){title.textContent="Welcome back";sub.textContent="Log in to your eFootball Dreamers account.";u.parentElement.style.display="none";u.required=false;submit.textContent="Log In →";sw.textContent="New to Dreamers?";btn.textContent="Create account"}else{title.textContent="Create your account";sub.textContent="Join the community with a real online account.";u.parentElement.style.display="block";u.required=true;submit.textContent="Create Account →";sw.textContent="Already have an account?";btn.textContent="Log in"}}
function join(){const m=authModal();setAuthMode("signup");m.classList.add("open")}
function login(){const m=authModal();setAuthMode("login");m.classList.add("open")}
function closeAuth(){const m=document.getElementById("dreamersAuthModal");if(m)m.classList.remove("open")}
async function handleAuthSubmit(e){e.preventDefault();const m=authModal(),msg=m.querySelector("#authMessage"),button=m.querySelector("#authSubmit");msg.className="auth-message";msg.textContent="Connecting securely…";button.disabled=true;try{const sb=await getSupabase(),email=m.querySelector("#authEmail").value.trim().toLowerCase(),password=m.querySelector("#authPassword").value;let result;if(authMode==="signup"){const username=m.querySelector("#authUsername").value.trim();result=await sb.auth.signUp({email,password,options:{data:{username}}});if(result.error)throw result.error;msg.textContent=result.data.session?"✓ Account created and you're logged in!":"✓ Account created. Check your email to confirm your account, then log in."}else{result=await sb.auth.signInWithPassword({email,password});if(result.error)throw result.error;msg.textContent="✓ Login successful. Welcome back!";setTimeout(closeAuth,900)}await refreshAuthUI()}catch(err){msg.className="auth-message auth-error";msg.textContent=err.message||"Something went wrong. Please try again."}finally{button.disabled=false}}
async function refreshAuthUI(){try{const sb=await getSupabase(),{data}=await sb.auth.getSession(),logged=!!data.session,buttons=document.querySelectorAll(".nav-actions button");if(buttons.length>=2){buttons[0].textContent=logged?"Logout":"Login";buttons[0].onclick=logged?logout:login;buttons[1].textContent=logged?"My Account":"Create Account";buttons[1].onclick=logged?showAccount:join}}catch(e){console.warn("Supabase auth unavailable",e)}}
async function logout(){const sb=await getSupabase();await sb.auth.signOut();await refreshAuthUI();alert("You have been logged out of eFootball Dreamers.")}
async function showAccount(){const sb=await getSupabase(),{data}=await sb.auth.getUser();if(data.user)alert("Logged in as: "+data.user.email)}
function eventInfo(name){alert(name+" details and registration are coming soon.")}
function react(btn){const n=btn.textContent.match(/\d+/);btn.textContent="♥ "+(n?Number(n[0])+1:1);btn.disabled=true}
function newPost(){alert("Posting will be available when community accounts are connected.")}
function toggleMenu(){document.getElementById("navLinks").classList.toggle("open")}
const firePlayers=[{name:"MBAPPÉ",role:"THE SPEEDSTER",number:10,image:"https://commons.wikimedia.org/wiki/Special:FilePath/Kylian_Mbappe_France_v_Paraguay_4_July_2026-124.jpg",goals:3,assists:2,saves:0,blocks:1,tackles:5},{name:"MESSI",role:"THE MAGICIAN",number:10,image:"https://commons.wikimedia.org/wiki/Special:FilePath/Lionel_Messi_Argentina_v_Egypt_7_July_2026-112.jpg",goals:2,assists:3,saves:0,blocks:2,tackles:6},{name:"RONALDO",role:"THE PHENOMENON",number:7,image:"https://commons.wikimedia.org/wiki/Special:FilePath/Cristiano_Ronaldo_Croatia_v_Portugal_2_July_2026-087.jpg",goals:2,assists:1,saves:0,blocks:3,tackles:4},{name:"NEYMAR",role:"THE SHOWMAN",number:10,image:"https://commons.wikimedia.org/wiki/Special:FilePath/Neymar_Junior_Brazil_V_Morocco_13_June_2026-145.jpg",goals:1,assists:4,saves:0,blocks:2,tackles:8}];
let fireIndex=0,matchSeconds=4044,homeScore=2,awayScore=1;
function fireScoreFor(p){return Math.min(99,70+p.goals*6+p.assists*3+p.saves*2+p.blocks*2+p.tackles)}
function matchClock(){matchSeconds=Math.min(5400,matchSeconds+1);const m=Math.floor(matchSeconds/60),s=matchSeconds%60,el=document.getElementById("matchMinute");if(el)el.textContent=m+":"+String(s).padStart(2,"0")}
function renderFire(){const p=firePlayers[fireIndex],score=fireScoreFor(p),ranked=firePlayers.map((x,i)=>({x,i,s:fireScoreFor(x)})).sort((a,b)=>b.s-a.s),img=document.getElementById("firePlayerImage");if(img){img.src=p.image;img.alt=p.name}const n=document.getElementById("firePlayerName");if(n)n.textContent=p.name;const r=document.getElementById("fireRole");if(r)r.textContent=p.role;const sc=document.getElementById("fireScore");if(sc)sc.textContent=score;const pos=document.getElementById("firePosition");if(pos)pos.textContent="#"+p.number;const reason=document.getElementById("fireReason");if(reason)reason.textContent=p.goals+" GOALS • "+p.assists+" ASSISTS • "+p.tackles+" TACKLES";const status=document.getElementById("fireStatus");if(status)status.textContent=p.name+" is leading";const stats=document.getElementById("fireStats");if(stats)stats.innerHTML='<div class="fire-stat"><b>'+p.goals+'</b><span>⚽ GOALS</span></div><div class="fire-stat"><b>'+p.assists+'</b><span>🎯 ASSISTS</span></div><div class="fire-stat"><b>'+p.saves+'</b><span>🧤 SAVES</span></div><div class="fire-stat"><b>'+p.blocks+'</b><span>🛡 BLOCKS</span></div><div class="fire-stat"><b>'+p.tackles+'</b><span>💪 TACKLES</span></div><div class="fire-stat"><b>'+score+'</b><span>🔥 FORM</span></div>';const board=document.getElementById("fireLeaderboard");if(board)board.innerHTML=ranked.map((v,pos)=>'<button type="button" class="fire-rank '+(v.i===fireIndex?'active':'')+'" onclick="selectFirePlayer('+v.i+')"><strong>'+v.s+'</strong><b>#'+(pos+1)+' '+v.x.name+'</b><small>'+v.x.goals+' G • '+v.x.saves+' S • '+v.x.blocks+' B • '+v.x.tackles+' T</small></button>').join("");const momentum=Math.max(35,Math.min(85,50+(score-85)*2)),hm=document.getElementById("homeMomentum"),am=document.getElementById("awayMomentum"),fill=document.getElementById("momentumFill");if(hm)hm.textContent=Math.round(momentum)+"%";if(am)am.textContent=Math.round(100-momentum)+"%";if(fill)fill.style.width=momentum+"%";const mt=document.getElementById("momentumText");if(mt)mt.textContent=momentum>=50?"DREAMERS FC":"RIVALS XI";const hs=document.getElementById("homeScore"),as=document.getElementById("awayScore");if(hs)hs.textContent=homeScore;if(as)as.textContent=awayScore}
function selectFirePlayer(i){fireIndex=i;renderFire()}function nextFirePlayer(){fireIndex=(fireIndex+1)%firePlayers.length;renderFire()}function fireEvent(type){const p=firePlayers[fireIndex];let eventText="";if(type==="goal"){p.goals++;homeScore++;eventText=p.name+" scores! ⚽ DREAMERS FC "+homeScore+" — "+awayScore}if(type==="save"){p.saves++;eventText=p.name+" makes a huge save! 🧤"}if(type==="block"){p.blocks++;eventText=p.name+" makes the block! 🛡"}if(type==="tackle"){p.tackles++;eventText=p.name+" wins the tackle! 💪"}fireIndex=firePlayers.map((x,i)=>({i,s:fireScoreFor(x)})).sort((a,b)=>b.s-a.s)[0].i;renderFire();const ev=document.getElementById("matchEvent");if(ev)ev.textContent=eventText}
document.addEventListener("DOMContentLoaded",async()=>{authModal();renderFire();setInterval(matchClock,1000);await refreshAuthUI()});
